/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcervoRouteImport } from './routes/acervo'
import { Route as CartaRouteImport } from './routes/carta'
import { Route as CartasRouteImport } from './routes/cartas'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LeitoresRouteImport } from './routes/leitores'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiCapaRouteImport } from './routes/api.capa'
import { Route as ConviteCodigoRouteImport } from './routes/convite.$codigo'
import { Route as LeitorUsuarioRouteImport } from './routes/leitor.$usuario'
import { Route as LerLivroIdRouteImport } from './routes/ler.$livroId'
import { Route as LivroLivroIdRouteImport } from './routes/livro.$livroId'
import { Route as RedefinirTokenRouteImport } from './routes/redefinir.$token'
import { Route as RetrospectivaAnoRouteImport } from './routes/retrospectiva.$ano'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcervoRoute = AcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaRoute = CartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => rootRouteImport,
} as any)
const CartasRoute = CartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LeitoresRoute = LeitoresRouteImport.update({
  id: '/leitores',
  path: '/leitores',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapaRoute = ApiCapaRouteImport.update({
  id: '/api/capa',
  path: '/api/capa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteCodigoRoute = ConviteCodigoRouteImport.update({
  id: '/convite/$codigo',
  path: '/convite/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const LeitorUsuarioRoute = LeitorUsuarioRouteImport.update({
  id: '/leitor/$usuario',
  path: '/leitor/$usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const LerLivroIdRoute = LerLivroIdRouteImport.update({
  id: '/ler/$livroId',
  path: '/ler/$livroId',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroLivroIdRoute = LivroLivroIdRouteImport.update({
  id: '/livro/$livroId',
  path: '/livro/$livroId',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirTokenRoute = RedefinirTokenRouteImport.update({
  id: '/redefinir/$token',
  path: '/redefinir/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrospectivaAnoRoute = RetrospectivaAnoRouteImport.update({
  id: '/retrospectiva/$ano',
  path: '/retrospectiva/$ano',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/carta': typeof CartaRoute
  '/cartas': typeof CartasRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/leitores': typeof LeitoresRoute
  '/novo': typeof NovoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/capa': typeof ApiCapaRoute
  '/convite/$codigo': typeof ConviteCodigoRoute
  '/leitor/$usuario': typeof LeitorUsuarioRoute
  '/ler/$livroId': typeof LerLivroIdRoute
  '/livro/$livroId': typeof LivroLivroIdRoute
  '/redefinir/$token': typeof RedefinirTokenRoute
  '/retrospectiva/$ano': typeof RetrospectivaAnoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/carta': typeof CartaRoute
  '/cartas': typeof CartasRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/leitores': typeof LeitoresRoute
  '/novo': typeof NovoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/capa': typeof ApiCapaRoute
  '/convite/$codigo': typeof ConviteCodigoRoute
  '/leitor/$usuario': typeof LeitorUsuarioRoute
  '/ler/$livroId': typeof LerLivroIdRoute
  '/livro/$livroId': typeof LivroLivroIdRoute
  '/redefinir/$token': typeof RedefinirTokenRoute
  '/retrospectiva/$ano': typeof RetrospectivaAnoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acervo': typeof AcervoRoute
  '/carta': typeof CartaRoute
  '/cartas': typeof CartasRoute
  '/conta': typeof ContaRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/leitores': typeof LeitoresRoute
  '/novo': typeof NovoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/capa': typeof ApiCapaRoute
  '/convite/$codigo': typeof ConviteCodigoRoute
  '/leitor/$usuario': typeof LeitorUsuarioRoute
  '/ler/$livroId': typeof LerLivroIdRoute
  '/livro/$livroId': typeof LivroLivroIdRoute
  '/redefinir/$token': typeof RedefinirTokenRoute
  '/retrospectiva/$ano': typeof RetrospectivaAnoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acervo'
    | '/carta'
    | '/cartas'
    | '/conta'
    | '/entrar'
    | '/esqueci-senha'
    | '/leitores'
    | '/novo'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/capa'
    | '/convite/$codigo'
    | '/leitor/$usuario'
    | '/ler/$livroId'
    | '/livro/$livroId'
    | '/redefinir/$token'
    | '/retrospectiva/$ano'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acervo'
    | '/carta'
    | '/cartas'
    | '/conta'
    | '/entrar'
    | '/esqueci-senha'
    | '/leitores'
    | '/novo'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/capa'
    | '/convite/$codigo'
    | '/leitor/$usuario'
    | '/ler/$livroId'
    | '/livro/$livroId'
    | '/redefinir/$token'
    | '/retrospectiva/$ano'
  id:
    | '__root__'
    | '/'
    | '/acervo'
    | '/carta'
    | '/cartas'
    | '/conta'
    | '/entrar'
    | '/esqueci-senha'
    | '/leitores'
    | '/novo'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/capa'
    | '/convite/$codigo'
    | '/leitor/$usuario'
    | '/ler/$livroId'
    | '/livro/$livroId'
    | '/redefinir/$token'
    | '/retrospectiva/$ano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcervoRoute: typeof AcervoRoute
  CartaRoute: typeof CartaRoute
  CartasRoute: typeof CartasRoute
  ContaRoute: typeof ContaRoute
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LeitoresRoute: typeof LeitoresRoute
  NovoRoute: typeof NovoRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCapaRoute: typeof ApiCapaRoute
  ConviteCodigoRoute: typeof ConviteCodigoRoute
  LeitorUsuarioRoute: typeof LeitorUsuarioRoute
  LerLivroIdRoute: typeof LerLivroIdRoute
  LivroLivroIdRoute: typeof LivroLivroIdRoute
  RedefinirTokenRoute: typeof RedefinirTokenRoute
  RetrospectivaAnoRoute: typeof RetrospectivaAnoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acervo': {
      id: '/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AcervoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta': {
      id: '/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof CartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartas': {
      id: '/cartas'
      path: '/cartas'
      fullPath: '/cartas'
      preLoaderRoute: typeof CartasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitores': {
      id: '/leitores'
      path: '/leitores'
      fullPath: '/leitores'
      preLoaderRoute: typeof LeitoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capa': {
      id: '/api/capa'
      path: '/api/capa'
      fullPath: '/api/capa'
      preLoaderRoute: typeof ApiCapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$codigo': {
      id: '/convite/$codigo'
      path: '/convite/$codigo'
      fullPath: '/convite/$codigo'
      preLoaderRoute: typeof ConviteCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitor/$usuario': {
      id: '/leitor/$usuario'
      path: '/leitor/$usuario'
      fullPath: '/leitor/$usuario'
      preLoaderRoute: typeof LeitorUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ler/$livroId': {
      id: '/ler/$livroId'
      path: '/ler/$livroId'
      fullPath: '/ler/$livroId'
      preLoaderRoute: typeof LerLivroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/$livroId': {
      id: '/livro/$livroId'
      path: '/livro/$livroId'
      fullPath: '/livro/$livroId'
      preLoaderRoute: typeof LivroLivroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir/$token': {
      id: '/redefinir/$token'
      path: '/redefinir/$token'
      fullPath: '/redefinir/$token'
      preLoaderRoute: typeof RedefinirTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrospectiva/$ano': {
      id: '/retrospectiva/$ano'
      path: '/retrospectiva/$ano'
      fullPath: '/retrospectiva/$ano'
      preLoaderRoute: typeof RetrospectivaAnoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcervoRoute: AcervoRoute,
  CartaRoute: CartaRoute,
  CartasRoute: CartasRoute,
  ContaRoute: ContaRoute,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LeitoresRoute: LeitoresRoute,
  NovoRoute: NovoRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCapaRoute: ApiCapaRoute,
  ConviteCodigoRoute: ConviteCodigoRoute,
  LeitorUsuarioRoute: LeitorUsuarioRoute,
  LerLivroIdRoute: LerLivroIdRoute,
  LivroLivroIdRoute: LivroLivroIdRoute,
  RedefinirTokenRoute: RedefinirTokenRoute,
  RetrospectivaAnoRoute: RetrospectivaAnoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
